spring:
  application:
    name: redd-projects-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:3.15.156.162}:${DB_PORT:5432}/${DB_NAME:gisdb}
    username: ${DB_USER:gisuser}
    password: ${DB_PASSWORD:gispassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:false}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

server:
  port: ${SERVER_PORT:8096}
